# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  name: EnvFile
  inputs:
    secureFile: '.env'

- script: |
    source $(EnvFile.secureFilePath)
    cd server/
    npm install
    npm run start
  displayName: 'npm install and build'
