version: '3.1'

services:

  backend:
    image: javo3000/javoserver:182
    ports:
      - 3001:3001
    networks:
      - localnet
    #volumes:
    #  - /tmp/back:/usr/src/app

  frontend:
    image: javo3000/javoclient:183
    ports: 
      - 3000:80
    networks:
      - localnet
    #volumes:
    #  - /tmp/front:/usr/src/app
    depends_on:
      - backend
  

  db:
    image: javo3000/javoapi:198
    ports:
      - 5000:5000
    networks:
      - localnet

  dbmanager:
    image: adminer
    ports:
      - 8085:8080
    networks:
      - localnet

networks:
  localnet:
    driver: overlay