version: '3.1'

services:

  backend:
    image: javo3000/javoserver:206
    ports:
      - 3001:3001
    networks:
      - localnet
    #volumes:
    #  - /tmp/back:/usr/src/app

  frontend:
    image: javo3000/javoclient:207
    ports: 
      - 80:80
    networks:
      - localnet
    #volumes:
    #  - /tmp/front:/usr/src/app
    depends_on:
      - backend

  dbmanager:
    image: adminer
    ports:
      - 8085:8080
    networks:
      - localnet

networks:
  localnet:
    driver: overlay